name: CI
on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup pnpm for all the virtual machine
        uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: Setup a especific node version
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'pnpm'

      - run: pnpm install --frozen-lockfile
      - run: pnpm run ci
